### ISSUE TITLE
GitHub API no longer using token authentication

### ISSUE THREAD

**Issue by tybenz** [ivanvc/gists-tmbundle#3]
According to [this](https://github.com/blog/1090-github-api-moving-on), GitHub is updating their API and dropping support for the old one, including dropping token authentication.

Any way you can switch the bundle to the new API?

**Comment by ivanvc** [comment]
Sure, let me think on how to add OAuth authentication to this bundle. Probably the authorization token will be required to be saved in an environment variable, or somewhere that the bundle can read it...
